joint_limits:
    front_left_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 0.24
      min_velocity: -0.24
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    
    rear_left_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 0.24
      min_velocity: -0.24
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0

    front_right_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 0.24
      min_velocity: -0.24
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0
    
    rear_right_joint:
      has_position_limits: false
      min_position: 0
      max_position: 0
      has_velocity_limits: true
      max_velocity: 0.24
      min_velocity: -0.24
      has_acceleration_limits: true
      max_acceleration: 2.0
      has_jerk_limits: false
      max_jerk: 0
      has_effort_limits: false
      max_effort: 0
      min_effort: 0

